route:
  receiver: telegram

receivers:
  - name: "telegram"
    telegram_configs:
      - send_resolved: true
        api_url: https://api.telegram.org
        # It's your bot token
        bot_token: ""
        # Add `myidbot` to your telegram group，and send `/getgroupid @myidbot` to get the chat id.
        chat_id: null
        parse_mode: ""
